### ISSUE TITLE
Issue with libpfm during bazel run --config=opt fleetbench/tcmalloc:empirical_driver

### ISSUE THREAD

**Issue by atharvabhanage12** [google/fleetbench#15]
using bazel 6.3.2
using gcc 12.3.0

DEBUG: /private/var/tmp/_bazel_athbha01/d016f079ed8063c5398a942b18f70a7b/external/rules_python/python/pip.bzl:47:10: pip_install is deprecated. Please switch to pip_parse. pip_install will be removed in a future release.
INFO: Repository libpfm instantiated at:
  Desktop/bechmark_fleetbech/fleetbench/WORKSPACE:110:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_athbha01/d016f079ed8063c5398a942b18f70a7b/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
WARNING: Download from https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz/download failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed but wanted 5da5f8872bde14b3634c9688d980f68bda28b510268723cc12973eedbab9fecc
ERROR: An error occurred during the fetch of repository 'libpfm':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_athbha01/d016f079ed8063c5398a942b18f70a7b/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz/download] to /private/var/tmp/_bazel_athbha01/d016f079ed8063c5398a942b18f70a7b/external/libpfm/temp3458073497591957110/download.tar.gz: Checksum was 251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed but wanted 5da5f8872bde14b3634c9688d980f68bda28b510268723cc12973eedbab9fecc
ERROR: /Desktop/bechmark_fleetbech/fleetbench/WORKSPACE:110:13: fetching http_archive rule //external:libpfm: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_athbha01/d016f079ed8063c5398a942b18f70a7b/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz/download] to /private/var/tmp/_bazel_athbha01/d016f079ed8063c5398a942b18f70a7b/external/libpfm/temp3458073497591957110/download.tar.gz: Checksum was 251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed but wanted 5da5f8872bde14b3634c9688d980f68bda28b510268723cc12973eedbab9fecc
ERROR: /private/var/tmp/_bazel_athbha01/d016f079ed8063c5398a942b18f70a7b/external/com_google_benchmark/BUILD.bazel:35:11: @com_google_benchmark//:benchmark depends on @libpfm//:libpfm in repository @libpfm which failed to fetch. no such package '@libpfm//': java.io.IOException: Error downloading [https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz/download] to /private/var/tmp/_bazel_athbha01/d016f079ed8063c5398a942b18f70a7b/external/libpfm/temp3458073497591957110/download.tar.gz: Checksum was 251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed but wanted 5da5f8872bde14b3634c9688d980f68bda28b510268723cc12973eedbab9fecc
ERROR: Analysis of target '//fleetbench/tcmalloc:empirical_driver' failed; build aborted: 
INFO: Elapsed time: 335.156s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (75 packages loaded, 703 targets configured)
ERROR: Build failed. Not running target

**Comment by andreas-abel** [comment]
This appears to be a temporary problem on SourceForge. The downloaded file (https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz/download) currently contains "We're sorry -- the Sourceforge site is currently in Disaster Recovery mode.  Please check back later."

**Comment by atharvabhanage12** [comment]
using bazel 6.3.2
using gcc 12.3.0

above issue is now fixed but now ended  up with this issue. please guide me. 

bazel run --config=opt fleetbench/tcmalloc:empirical_driver  
WARNING: Output base '  /.cache/bazel/_bazel_athbha01/8f4a24188ec25142b28e12f4ec4ee68a' is on NFS. This may lead to surprising failures and undetermined behavior.
DEBUG:   /.cache/bazel/_bazel_athbha01/8f4a24188ec25142b28e12f4ec4ee68a/external/rules_python/python/pip.bzl:47:10: pip_install is deprecated. Please switch to pip_parse. pip_install will be removed in a future release.
INFO: Analyzed target //fleetbench/tcmalloc:empirical_driver (79 packages loaded, 2119 targets configured).
INFO: Found 1 target...
INFO: From Compiling absl/strings/internal/str_format/float_conversion.cc:
In file included from /usr/include/string.h:638,
                 from /arm/tools/gnu/gcc/12.2.0/rhe7-x86_64/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/cstring:42,
                 from external/com_google_absl/absl/strings/internal/str_format/extension.h:23,
                 from external/com_google_absl/absl/strings/internal/str_format/float_conversion.h:18,
                 from external/com_google_absl/absl/strings/internal/str_format/float_conversion.cc:15:
In function 'void* memset(void*, int, size_t)',
    inlined from 'absl::str_format_internal::FormatSinkImpl::Append(size_t, char)::<lambda(size_t)>' at external/com_google_absl/absl/strings/internal/str_format/extension.h:82:13,
    inlined from 'void absl::str_format_internal::FormatSinkImpl::Append(size_t, char)' at external/com_google_absl/absl/strings/internal/str_format/extension.h:88:19,
    inlined from 'void absl::str_format_internal::{anonymous}::FormatFNegativeExpSlow(absl::uint128, int, const FormatState&)' at external/com_google_absl/absl/strings/internal/str_format/float_conversion.cc:616:49:
/usr/include/bits/string3.h:81:30: warning: call to '__warn_memset_zero_len' declared with attribute warning: memset used with constant zero length parameter; this could be due to transposed parameters [-Wattribute-warning]
   81 |       __warn_memset_zero_len ();
      |       ~~~~~~~~~~~~~~~~~~~~~~~^~
INFO: From Compiling fleetbench/benchmark_main.cc:
fleetbench/benchmark_main.cc: In function 'int main(int, char**)':
fleetbench/benchmark_main.cc:26:16: warning: unused variable 'background' [-Wunused-variable]
   26 |   static auto* background =
      |                ^~~~~~~~~~
INFO: From Compiling fleetbench/tcmalloc/empirical_driver.cc:
In file included from external/com_google_absl/absl/base/macros.h:36,
                 from external/com_google_absl/absl/base/dynamic_annotations.h:54,
                 from external/com_google_absl/absl/base/internal/spinlock.h:37,
                 from fleetbench/tcmalloc/empirical_driver.cc:32:
external/com_google_absl/absl/log/internal/check_op.h: In instantiation of 'constexpr std::string* absl::log_internal::Check_GTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int; std::string = std::__cxx11::basic_string<char>]':
fleetbench/tcmalloc/empirical_driver.cc:127:5:   required from here
external/com_google_absl/absl/log/internal/check_op.h:341:43: warning: comparison of integer expressions of different signedness: 'const long unsigned int' and 'const int' [-Wsign-compare]
  341 | ABSL_LOG_INTERNAL_CHECK_OP_IMPL(Check_GT, >)
external/com_google_absl/absl/base/optimization.h:179:58: note: in definition of macro 'ABSL_PREDICT_TRUE'
  179 | #define ABSL_PREDICT_TRUE(x) (__builtin_expect(false || (x), true))
      |                                                          ^
external/com_google_absl/absl/log/internal/check_op.h:341:1: note: in expansion of macro 'ABSL_LOG_INTERNAL_CHECK_OP_IMPL'
  341 | ABSL_LOG_INTERNAL_CHECK_OP_IMPL(Check_GT, >)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR:   /test_bench/google-fleetbench-b1a91dd/fleetbench/tcmalloc/BUILD:48:8: Linking fleetbench/tcmalloc/empirical_driver failed: (Exit 1): gcc failed: error executing command (from target //fleetbench/tcmalloc:empirical_driver) /arm/tools/gnu/gcc/12.2.0/rhe7-x86_64/bin/gcc @bazel-out/k8-opt/bin/fleetbench/tcmalloc/empirical_driver-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/bin/ld: /arm/tools/gnu/gcc/12.2.0/rhe7-x86_64/lib/gcc/x86_64-pc-linux-gnu/12.2.0/libgcc.a(_muldi3.o): unable to initialize decompress status for section .debug_info
/bin/ld: /arm/tools/gnu/gcc/12.2.0/rhe7-x86_64/lib/gcc/x86_64-pc-linux-gnu/12.2.0/libgcc.a(_muldi3.o): unable to initialize decompress status for section .debug_info
/bin/ld: /arm/tools/gnu/gcc/12.2.0/rhe7-x86_64/lib/gcc/x86_64-pc-linux-gnu/12.2.0/libgcc.a(_popcountsi2.o): unable to initialize decompress status for section .debug_info
/bin/ld: /arm/tools/gnu/gcc/12.2.0/rhe7-x86_64/lib/gcc/x86_64-pc-linux-gnu/12.2.0/libgcc.a(_popcountsi2.o): unable to initialize decompress status for section .debug_info
/arm/tools/gnu/gcc/12.2.0/rhe7-x86_64/lib/gcc/x86_64-pc-linux-gnu/12.2.0/libgcc.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
Target //fleetbench/tcmalloc:empirical_driver failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 102.390s, Critical Path: 96.84s
INFO: 387 processes: 97 internal, 290 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target

**Comment by atharvabhanage12** [comment]
Later this worked as sourceforge was Live!!
