### ISSUE TITLE
compile fleetbench/tcmalloc:empirical_driver failed

### ISSUE THREAD

**Issue by lifengxiang1025** [google/fleetbench#17]
When I run: `bazel run --config=opt fleetbench/tcmalloc:empirical_driver --config=clang`. It causes error like 

ld.lld:_ error: undefined symbol: std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)
\>\>\> referenced by common.cc
\>\>\>               bazel-out/k8-opt-clang/bin/fleetbench/common/_objs/common/common.o:(fleetbench::GetMatchingFiles[abi:cxx11](std::basic_string_view<char, std::char_traits<char>>, std::basic_string_view<char, `std::char_traits<char>>))

It seems to need to add ldflags `-lstdc++fs`

**Comment by rjogrady** [comment]
You likely need to install a more recent version of clang. Fleetbench recommends LLVM 14 or higher.
