### ISSUE TITLE
libc output - time_unit is ns instead of seconds 

### ISSUE THREAD

**Issue by BatelOved** [google/fleetbench#19]
In the first line, the cpu_time is 0.0982076 ns, meaning less the 1 cpu cycle, therefore doesn't make sense of course..

I would expect to have cpu_time ~ bytes / bytes_per_second, and it is the case, just that cpu_time should be in seconds unit and not in nanoseconds as the time_unit suggests.

I would suggest to check that in the other benchmarks as well.

Thanks.

![image](https://github.com/google/fleetbench/assets/71281877/88fdda9d-2fe7-4a37-baf0-11bad5a6dbb4)

**Comment by andreas-abel** [comment]
For the libc benchmarks, the value in cpu_time is the time it takes to process one byte of data (see https://github.com/google/fleetbench/tree/main/fleetbench/libc#L311). Therefore, it can be less than one cycle.
