### ISSUE TITLE
[AArch64] Proto fails with segmentation fault

### ISSUE THREAD

**Issue by madhur13490** [google/fleetbench#26]
`build --config=clang --sandbox_debug --config=arm --custom_malloc="@bazel_tools//tools/cpp:malloc" fleetbench/proto:proto_benchmark`

With the command, I see 

```
+ ./make install
bazel-out/aarch64-opt-exec-ST-a828a81199fe/bin/external/rules_foreign_cc/toolchains/make_tool_foreign_cc/build_script.sh: line 21:  3778 Segmentation fault      (core dumped) ./make install
_____ END BUILD LOGS _____

```

on an AArch64 machine.

Is this a known issue? How do I fix it? I don't know if `fleetbench` is tested on AArch64 platform.

**Comment by rjogrady** [comment]
This isn't a known issue, but yes, Fleetbench should be able build and run on an AArch64 system.

I think we would need some more details to help diagnose the error.

Can you build and run other binaries successfully with bazel, or is this unique to Fleetbench?
Do you have sufficient disk and RAM available on the machine where you are trying to build?

And if you can provide the version of your distro and tools e.g. `uname -a`, `clang -v`, `make -v`, `bazel --version` we might be able to narrow down if there are any differences.

We have tested with gcc 13.2, clang 17, and bazel version 7 on Debian.

**Comment by madhur13490** [comment]
> This isn't a known issue, but yes, Fleetbench should be able build and run on an AArch64 system.
> 
> I think we would need some more details to help diagnose the error.
> 
> Can you build and run other binaries successfully with bazel, or is this unique to Fleetbench? Do you have sufficient disk and RAM available on the machine where you are trying to build?
> 
> And if you can provide the version of your distro and tools e.g. `uname -a`, `clang -v`, `make -v`, `bazel --version` we might be able to narrow down if there are any differences.
> 
> We have tested with gcc 13.2, clang 17, and bazel version 7 on Debian.

I have enough space on my disk and only fleetbench fails with bazel. I am on Ubuntu 22.04, clang 20, make 4.2, bazel 7.4.0.

Is there a bot/CI where I can see last build results? If it has build config then let me know.

**Comment by rjogrady** [comment]
Thanks for the info.

Unfortunately our builders are internal only at this time. We can look into potentially having a Github runner as well.

One thing you could try is to see if this problem is for some reason specific to the make rules, building with `--define=pfm=0`
as a flag to bazel build. The libpfm library is compiled with make, while the rest are native bazel build rules. That might tell us something.

**Comment by madhur13490** [comment]
Ok, clean followed by the above flag helped. The build went through. 

I have another question. How do I pass my custom compiler built locally on the disk pass to bazel? I want to understand some behavior with upstream LLVM trunk.

**Comment by madhur13490** [comment]
Followup question. How do I pass compiler flags to the build? I don't see any pointers in the README. Specifically, I want to pass "-Ofast" to the build.

**Comment by madhur13490** [comment]
I think I found answer to myself. exporting CC, CXX helps and it picks the binaries I want. Closing this issue. Thanks for all the help!
