### ISSUE TITLE
Abseil flags are not parsed

### ISSUE THREAD

**Issue by dhschall** [google/fleetbench#27]
I was running the `libc` benchmark, where the cache size could not be detected. The error suggested specifying the cache size manually using `--L1_data_size` . This didn't work because the flags were not parsed.

Adding
```
absl::ParseCommandLine(argc, argv);
```
after the `benchmark::Initialize(&argc, argv)` in `benchmark_main.cc` and adding the necessary headers fixed the problem for me.

**Comment by andreas-abel** [comment]
Thanks for reporting this!

Fixed in https://github.com/google/fleetbench/commit/930d112fb3124c172feaa1fc81b26d2bf0ae298d
